version: '3.8'
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'